FROM archlinux:latest

COPY mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syy
RUN pacman --noconfirm -S git gcc cmake make r gcc-fortran pkg-config otf-latin-modern python python-pip

# R dependencies
RUN R -e 'install.packages(c("ggplot2", "egg", "xtable", "extrafont", "plyr", "dplyr", "reshape2", "grid", "ggpubr", "GGally", "showtext", "plotly", "igraph"), repos="https://cloud.r-project.org/")'

# code
RUN git clone https://github.com/thobl/external-validity.git ext_val
WORKDIR /ext_val
RUN git submodule init
RUN git submodule update

# run + dependencies
WORKDIR /ext_val/run
RUN pip3 install .
WORKDIR /ext_val

# building c++
RUN ./build.sh

RUN pacman -Scc

ENTRYPOINT tail -f /dev/null

